language: ruby
rvm:
- 2.1.2
bundler_args: "--without production"
cache: bundler
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec
notifications:
  email:
    recipients:
    - matias@munki.cl
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: IH2NHNk+wtavp2rovIvyzSnSPTP4M0nWLyBBj3UGgX5MqxuqL+dIJC61lgvoy4z0+BGxfwL+hrQ4YlGx63fbBACbcIG8xsdQSDOTDpAnMBpDmEobfKM0HT4rE3dXpkEm+0Choudw0rxf4eA/0mbqw468b9Jnl4xh6zIhAA/LwgM=
  app: viverelajacion
  on:
    repo: MunkiStudio/viverelajacion
env:
  secure: F8vYrbseRQL5ER2zRE4TMvh5d5i2L6J9UFbiH1dKqUzw+pjziNnZ8nP/bYTPLU4tKWJHrY923zVYa5KlifdaCMTN+nqOzo9/RUNHjugyTY7kPE2wHqMYUAwqBE0hHf2JLaN6aMDtOx3n2KynmrqVbhxpavGAOp8yHcJvtNuzqxA=
  MANDRILL_USERNAME: apps@munki.cl
  REDISTOGO_URL: redis://redistogo:48f69b364c0e09e5eb91baca4846bf2b@grideye.redistogo.com:9726/
