Tip.create!([
  {titulo: "Tu programa de entrenamiento", image: nil, texto: "<p style=\"font-family: 'Open Sans', sans-serif; font-size: medium;\">Un programa de ejercicio f&iacute;sico en el &aacute;mbito no competitivo contribuye al fomento de <strong>h&aacute;bitos de vida</strong> m&aacute;s saludables.</p>\r\n<p style=\"font-family: 'Open Sans', sans-serif; font-size: medium;\">Sumar treinta minutos de actividad f&iacute;sica diaria ayuda a mejorar la salud. Este tipo de actividad f&iacute;sica regulada, mejora la funci&oacute;n cardiorespiratoria, aumenta la fuerza muscular, reduce la grasa corporal y disminuye el riesgo de <em>enfermedades cardiovasculares y metab&oacute;licas</em>.</p>", portada_file_name: "integrating_technology_into_your_fitness_plan_to_optimize_workouts_0.jpg", portada_content_type: "image/jpeg", portada_file_size: 122901, portada_updated_at: "2014-05-09 13:11:51", portada_meta: "BAh7CDoNb3JpZ2luYWx7CDoKd2lkdGhpAicDOgtoZWlnaHRpAlICOglzaXpl\naQMV4AE6CnNtYWxsewg7BmkByDsHaQHIOwhpArqpOgpsYXJnZXsIOwZpAqwD\nOwdpArQCOwhpAzY1Ag==\n"},
  {titulo: "Aumenta tu actividad física", image: nil, texto: "<p><span style=\"font-family: 'Open Sans', sans-serif; font-size: medium;\">La actividad f&iacute;sica permanente colabora en el equilibrio energ&eacute;tico para un peso saludable, reduciendo el porcentaje de grasa corporal, entregando una mejor forma f&iacute;sica, proporcionando una masa y composici&oacute;n corporal m&aacute;s sana.</span></p>", portada_file_name: "joggin.jpg", portada_content_type: "image/jpeg", portada_file_size: 21971, portada_updated_at: "2014-05-09 13:12:47", portada_meta: "BAh7CDoNb3JpZ2luYWx7CDoKd2lkdGhpAucBOgtoZWlnaHRpAjoBOglzaXpl\naQLTVToKc21hbGx7CDsGaQHIOwdpAcg7CGkCGR06Cmxhcmdlewg7BmkCrAM7\nB2kCXgI7CGkCH7Q=\n"},
  {titulo: "Cuida tu salud", image: nil, texto: "<p><span style=\"font-family: 'Open Sans', sans-serif; font-size: medium;\">La actividad f&iacute;sica es un factor determinante en el consumo de energ&iacute;a, por lo que es importante para conseguir el equilibrio energ&eacute;tico y el control del peso. Las personas m&aacute;s activas presentan tasas menores de mortalidad, cardiopat&iacute;a coronaria, hipertensi&oacute;n, accidente cardiovascular, diabetes tipo II y s&iacute;ndrome metab&oacute;lico.</span></p>", portada_file_name: "final_actividad.jpg", portada_content_type: "image/jpeg", portada_file_size: 63850, portada_updated_at: "2014-05-09 13:13:23", portada_meta: "BAh7CDoNb3JpZ2luYWx7CDoKd2lkdGhpAowCOgtoZWlnaHRpAlYBOglzaXpl\naQJq+ToKc21hbGx7CDsGaQHIOwdpAcg7CGkCqU46Cmxhcmdlewg7BmkCrAM7\nB2kC7QE7CGkD7LQB\n"},
  {titulo: "Mejora tu vida", image: nil, texto: "<p style=\"font-family: 'Open Sans', sans-serif; font-size: medium;\">Las personas que realizan una actividad f&iacute;sica presentan menor porcentaje de adiposidad que las menos activas.</p>\r\n<p style=\"font-family: 'Open Sans', sans-serif; font-size: medium;\">Una mejor forma f&iacute;sica proporciona una masa y composici&oacute;n corporal mas sana.</p>\r\n<p style=\"font-family: 'Open Sans', sans-serif; font-size: medium;\">La actividad f&iacute;sica permanente incrementa el gasto cal&oacute;rico y facilita la disminuci&oacute;n del tejido graso. El exceso de grasa corporal conlleva riesgos para la salud.</p>", portada_file_name: "saludable.jpg", portada_content_type: "image/jpeg", portada_file_size: 71327, portada_updated_at: "2014-05-09 13:14:05", portada_meta: "BAh7CDoNb3JpZ2luYWx7CDoKd2lkdGhpAlAFOgtoZWlnaHRpAlMDOglzaXpl\naQOfFgE6CnNtYWxsewg7BmkByDsHaQHIOwhpAp4ZOgpsYXJnZXsIOwZpAqwD\nOwdpAkwCOwhpAqC1\n"},
  {titulo: "Deja el sedentarismo", image: nil, texto: "<p style=\"font-family: 'Open Sans', sans-serif; font-size: medium;\">La actividad f&iacute;sica moderada previene el desarrollo de resistencia a la insulina y la diabetes tipo II y mejora el control de la glucemia.</p>\r\n<p style=\"font-family: 'Open Sans', sans-serif; font-size: medium;\">La inactividad f&iacute;sica constituye el cuarto factor de riesgo m&aacute;s importante de mortalidad en todo el mundo.</p>\r\n<p style=\"font-family: 'Open Sans', sans-serif; font-size: medium;\">Los adultos inactivos o con limitaciones vinculadas a enfermedades mejoran su salud realizando un cierto tipo de actividad f&iacute;sica controlada.</p>", portada_file_name: "Services_-_Executive_Health_and_Wellness.jpg", portada_content_type: "image/jpeg", portada_file_size: 171925, portada_updated_at: "2014-05-09 13:14:57", portada_meta: "BAh7CDoNb3JpZ2luYWx7CDoKd2lkdGhpAkAGOgtoZWlnaHRpAioEOglzaXpl\naQOVnwI6CnNtYWxsewg7BmkByDsHaQHIOwhpAiFFOgpsYXJnZXsIOwZpAqwD\nOwdpAnICOwhpA/yjAQ==\n"}
])
AdminUser.create!([
  {email: "admin@viverelajacion.cl", encrypted_password: "$2a$10$xXpOWbO6y2msXr4qmN.aleIDken2lF9HjUX6ISv2dGxL4fs0z3X6W", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil}
])
